server:
  port: 9099 #端口
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/job_time?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: manager
      initialSize: 1  #初始化大小
      minIdle: 1  #空闲连接池的大小
      maxActive: 50 #最大激活数量
  servlet:
    multipart:
      max-file-size: 50MB #单个文件上传大小限制
      max-request-size: 500MB #单次请求上传文件大小限制
#MyBatis配置文件
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/*.xml
#日志打印SQL
logging:
  level:
     com.job: debug  #日志级别
  config: classpath:logback.xml  #加载指定日志文件
system:
  domainName: http://127.0.0.1 #域名
  picPath: /opt/tomcat/webapps/mes  #上传图片路径
swagger:
  enable: true #是否开启swagger
fileSavePath: C:/photo/

resourcePath: /resource


appId: 1400111151
appKey: e1984a557f3ed83fb554ed1f76fe92cb
templateId: 153000
smsSign: "小蜜蜂一站式平台"

wx:
  notifyUrl: http://localhost/wx/notify #微信回调地址
  appId: wxc8e1a3732b85cd01
  appKey: a9eb523e05e230c6443a2526f8ccb511
zfb:
  returnUrl: http://www.xxx.com/alipay/return_url.do  #支付宝回调页面
  notifyUrl: http://localhost/notify                  #支付宝回调地址
  url: https://openapi.alipay.com/gateway.do  #支付宝的网关地址
  appId: 2016112003031087
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCcEEDufmYOAlO4uVr0t2mR8fELDTArJsmEVD5WL3UuPFnROTmY2NxqLHfL8RZvif8xGPj+Xkr02H8HvLKlUgvlQ56QCycTkDoMGY5iWUZElPfRIOvemimSWcfPlj+8/9JjeLJfDIzm36/naBwTKhcTTgSHivjqvyldiSqajwZDjQhtZ1s0X2Puv8u8pq5sLw/eNc1pMw+ekcILvpdoWAZa9rAb8S/pZ1JBq/LuEwKjkVrZGaUvL56bSiB+8OMXFuBA9HSiaLFDGhUf+xnGnpWuqFN7luOySh0fbxbM0WO89wKYc1BkXtDnFHprv60fMm1lsyhxhMygV7GpiSvmTi0/AgMBAAECggEAHa2dm30gDUP2BegB2w3SHrYC39YnNd2PbwHSRPOLdjp13iriwCVlbS99rKPxX06/3+de2oi1+m/9YExLMNM0fenpCn2Eddz0nP5zLFLL4RjvM67uDAwHIdS/AcQR5PBFYzM9wIOTfAhH3FrZE+/qKXqps9kC0yl9RVNjbbcLOucXqHE+F6xuCzS1EvjXLH3aS52tkwBiDmgQCQmaM2unYnteBt+e+06R6niWnb0HwTEeSJ7AHoV6F8fXijLdSvzaQ5RmRv6t4l9S+kEvlS8XT1ifYk5KWuyi9xkxfBiIxSNRNg7UXenOQht4p8bNeTzjBa39wBwISCQyPZoKS0gcoQKBgQDdodWhvhiULqNnaxdF1tMV2hyloSLJRUx4pVkYQibM+MQvA7SenTtkdCrqS7J+n5ygUpNw/xRdSOd+mLdAjUG/9/XC0IDVwe/EPYcS48LBQjsRfLQpspw0HqgfUYTelMn5xa9EGv7FjfzgdJYt8+tGRCmhBUDswISTrLqFJPBz0QKBgQC0Q4eQ+lKblZN2DUjJSF8vdBuYiVp3jFpqBEfPcVVhRWI1yYLMrrcMFDx3fHyLMz5WSrAsj8s3MJ4XaZNDzqlo/Z34jeqiB8PPZ25XJurF+XDWYkTLmQmA/We/hcY6Jg70n73bQtGxbBPTqNSjN6LXdk8PoHv7424W8jkTTo4kDwKBgDDFqlN7l8EUOlVJ1cdCrRUD+IXiXdtY6qkqCd8yv4Mfw1xtPlQhWa6TedYxbkg7K6aERXn6SCr3HipXxQvpieyKzoReiduAYBkZSR45DOSmhIUmoicC7SjzDiBGOi0ZJRFYFWexYRtsUZe7UEkwgjfmTBrpIw52lzZALpOaO2fhAoGANqG4tlGHM6vzUvXXt1j9sA4KRwJpro2U4UiG0vHQJHi4uQBnac0RoNGJOdU6kZ1oKRLdrcOunP1ZDFNs1EIPycgDVk78azrbN0JriHI8+N8OOYryupmY7cTe6oaKexkJs02uZoMrtg/BOoaSWx0DdzVd5KiIquBUfxPOBHHsVjUCgYEAzcUWCWTaIiRN4gSSlpNntepzaaYt0dk9jQd8A11wcVojETg7EyNX4vmerFNxJkx6I1eTcKH+qF3DVGXvnfcfTSLxFJv9D1UaqCMMht3UKGy+AjuA8ao24FPGczW0uz7zSUoZdp5B5zVoSORIvAR2lgynNqjwCmJLZ7Z0TR07j00=
  appPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkruNP9P7Uh4K0HNeaSadLoWAkroaUTdZXjjclPx7VPa+OsTu9iKbesSfnK+7GJVX+Mq6AC8nXP7MkFfHhiGJ0lF/q+dIW2Jt87vxlAjm4joZVM06MbkHRGeyuXYIn5Bpi9uqhJUmk5/mqa/LtgQS4akPc/K8IhQ1ZQDN/v1zQqveKMIVXF5fh57Q5h2ZgrYvb6CTCWo2NTrmG7k2fbQZJj0W7vreTlVe3KN05ngxJo1V1vSiYaTQm72UTOV9RoWE1GM9PHcGSMRPOp5HKD/F9/Kj9BfaGa7yRhmljRxLSIdXxQ3bX75ULSeoDwPDT+fKyhwCS759n65kniWtR4XlTQIDAQAB
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmDGgvK0cG0MXqqVqWG9WnSeouwmBqA8frf0GBAWviEHM9mG5SDZ0uJmmPVX3yAvD5bofm9gJl2+4s3RInxMJctgDVdSZUSZSwIo0gLPuxqDpIVOQCwn5y18XWbLCjqnK5D0oWI5I77P6yVDpyLV8Px/5SO4f2wxuA3M56JpdhPoePHecePzjGy4PLnR5DfJG+Yd8MWdpps+5Jn1PGBZjK3qDoThG8coQtqtq/g9INBFVajvZ/g6odkeP8uoE7PKv1h3ut44xKjeO9TPuvQG5izVAbRunKWcqoF6NJZfRDe8hEVNKZv4f8ag2aMIEyCN075rwnZ0fA06fSbXpc62iYQIDAQAB
